version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admlinux
      MYSQL_PASSWORD: admpassword
    ports:
      - "3307:3306"  # puerto 3306 de MySQL al 3307 de la pc
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  php:
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Nginx en el puerto 8081
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
